### ISSUE TITLE
The throughput is extremely low

### ISSUE THREAD

**Issue by zxgx** [PersiaML/PERSIA#233]
I adopted Persia to implement a DLRM and run it over Criteo Kaggle dataset.  
I set batch size to 1024, and below is the content of `docker-compose.yml`:
```yaml
version: "3.2"
services:
  persia_nats_service:
    image: nats:latest
    deploy:
      replicas: 1

  data_loader1:
    env_file:
      - .docker.env
    depends_on:
      - nn_worker
      - embedding_worker
      - persia_nats_service
    image: persia-dlrm
    command: persia-launcher data-loader --replica-index 0 --replica-size 2
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ../criteo_kaggle
        target: /workspace/criteo_kaggle
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  data_loader2:
    env_file:
      - .docker.env
    depends_on:
      - nn_worker
      - embedding_worker
      - persia_nats_service
    image: persia-dlrm
    command: persia-launcher data-loader --replica-index 1 --replica-size 2
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ../criteo_kaggle
        target: /workspace/criteo_kaggle
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nn_worker:
    env_file:
      - .docker.env
    environment:
      NCCL_SOCKET_IFNAME: eth0
      CUBLAS_WORKSPACE_CONFIG: :4096:8
    image: persia-dlrm
    command: persia-launcher nn-worker --nproc-per-node 1 --nnodes 1 --node-rank 0
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ../criteo_kaggle
        target: /workspace/criteo_kaggle
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  embedding_worker1:
    env_file:
      - .docker.env
    depends_on:
      - embedding_parameter_server
    image: persia-dlrm
    command: >
      bash -c "persia-launcher embedding-worker --embedding-config $$PERSIA_EMBEDDING_CONFIG
      --global-config $$PERSIA_GLOBAL_CONFIG --replica-index 0 --replica-size 2"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ../criteo_kaggle
        target: /workspace/criteo_kaggle

  embedding_worker2:
    env_file:
      - .docker.env
    depends_on:
      - embedding_parameter_server
    image: persia-dlrm
    command: >
      bash -c "persia-launcher embedding-worker --embedding-config $$PERSIA_EMBEDDING_CONFIG
      --global-config $$PERSIA_GLOBAL_CONFIG --replica-index 1 --replica-size 2"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ../criteo_kaggle
        target: /workspace/criteo_kaggle

  embedding_parameter_server1:
    env_file:
      - .docker.env
    image: persia-dlrm
    command: >
      bash -c "persia-launcher embedding-parameter-server --embedding-config $$PERSIA_EMBEDDING_CONFIG
      --global-config $$PERSIA_GLOBAL_CONFIG --replica-index 0 --replica-size 2"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ../criteo_kaggle
        target: /workspace/criteo_kaggle

  embedding_parameter_server2:
    env_file:
      - .docker.env
    image: persia-dlrm
    command: >
      bash -c "persia-launcher embedding-parameter-server --embedding-config $$PERSIA_EMBEDDING_CONFIG
      --global-config $$PERSIA_GLOBAL_CONFIG --replica-index 1 --replica-size 2"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: ../criteo_kaggle
        target: /workspace/criteo_kaggle
```
Here's a screenshot of the running process
![image](https://user-images.githubusercontent.com/34452939/177136221-98c5020c-46a6-4d81-aa09-ee5554830bd0.png)

As you can see, the throughput is about 30 it/s. Since the batch size is 1024, the throughput is only half of the results reported in your paper. 
I also notice that the logger kept warning that `the local forwarded queue` is empty, and these processes didn't cost any GPU memory.
Is there any problem about my settings or, do you guys have any suggestions on how to improve the throughput?
